SET CHARSET 'utf8';

CREATE DATABASE IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `tests` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE tests.`my_table` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`unq` VARCHAR(128) NOT NULL,
	`name` VARCHAR(300) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `unq` (`unq`)
)
ENGINE=InnoDB;