services:

    haxe:
        restart: always
        build:
            context: ./docker/haxe/
            dockerfile: dockerfile
        environment:
            KEEP_CONTAINER_ALIVE: "yes"
        volumes:
            - ./:/repo
            - ./docker/shared:/docker-shared
            - ./acerola:/acerola
            - ./docs:/acerola/docs

    mysql:
        restart: always
        build:
            context: ./docker/mysql/
            dockerfile: dockerfile
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        ports:
            - "${MYSQL_PORT}:3306"

    mysql9:
        restart: always
        build:
            context: ./docker/mysql9/
            dockerfile: dockerfile
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        ports:
            - "${MYSQL_PORT9}:3306"